### ISSUE TITLE
XMPP Upload not working without ydl_opts

### ISSUE THREAD

**Issue by Dominion0815** [gjedeer/xmpp-youtube-dl-bot#6]
Hi,

I have this error with these default settings and without ydl_opts:

# Send downloaded file by XMPP HTTP Upload
send_after_download = True

# After HTTP Upload is completed, delete the file from local disk
delete_after_send = True

```
Traceback (most recent call last):
  File "bot.py", line 251, in <module>
    cl.Process(.1)
  File "/usr/lib/python2.7/dist-packages/xmpp/dispatcher.py", line 303, in dispatch
    handler['func'](session,stanza)
  File "bot.py", line 118, in messageCB
    ydl.download([body.strip()])
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2019, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 863, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1644, in process_video_result
    self.process_info(new_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1920, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 342, in real_download
    return download()
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 334, in download
    'elapsed': time.time() - ctx.start_time,
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 374, in _hook_progress
    ph(status)
  File "bot.py", line 81, in ytdl_progress_hook
    if settings.send_after_download and not is_conversion_enabled():
  File "bot.py", line 73, in is_conversion_enabled
    return settings.ydl_opts and 'postprocessors' in settings.ydl_opts and len(settings.ydl_opts['postprocessors']) > 0
AttributeError: 'module' object has no attribute 'ydl_opts'
```

Thank you very much in advanced
Dominion

**Comment by gjedeer** [comment]
Then add:

    ytdl_opts = {}

to the settings
